In [14]:
import pandas as pd
from bs4 import BeautifulSoup
import requests

In [65]:
table = pd.read_html("https://en.wikipedia.org/wiki/List_of_postal_codes_of_Canada:_M")
df = table[0]
df.head()

  Postcode           Borough     Neighbourhood
0      M1A      Not assigned      Not assigned
1      M2A      Not assigned      Not assigned
2      M3A        North York         Parkwoods
3      M4A        North York  Victoria Village
4      M5A  Downtown Toronto      Harbourfront

In [69]:
df=df[df.Borough != 'Not assigned']
df = df.sort_values(by=['Postcode','Borough'])

df.reset_index(inplace=True)
df.drop('index',axis=1,inplace=True)

df

    Postcode      Borough   Neighbourhood
0        M1B  Scarborough           Rouge
1        M1B  Scarborough         Malvern
2        M1C  Scarborough  Highland Creek
3        M1C  Scarborough      Rouge Hill
4        M1C  Scarborough      Port Union
..       ...          ...             ...
205      M9V    Etobicoke     Mount Olive
206      M9V    Etobicoke     Silverstone
207      M9V    Etobicoke   South Steeles
208      M9V    Etobicoke     Thistletown
209      M9W    Etobicoke       Northwest

[210 rows x 3 columns]

In [71]:
df=df.groupby(['Postcode','Borough'])['Neighbourhood'].apply(list)
df=df.sample(frac=1).reset_index()
df['Neighbourhood']=df['Neighbourhood'].str.join(',')
df.loc[df['Neighbourhood'] == "Not assigned"] = df['Borough']
df

,Postcode,Borough,Neighbourhood
0,M1P,Scarborough,"Dorset Park,Scarborough Town Centre,Wexford He..."
1,M3H,North York,"Bathurst Manor,Downsview North,Wilson Heights"
2,M3M,North York,Downsview Central
3,M5A,Downtown Toronto,Harbourfront
4,M4X,Downtown Toronto,"Cabbagetown,St. James Town"
...,...,...,...
98,M2P,North York,York Mills West
99,M9W,Etobicoke,Northwest
100,M4Y,Downtown Toronto,Church and Wellesley
101,M1S,Scarborough,Agincourt
102,M4K,East Toronto,"The Danforth West,Riverdale"

In [87]:
df.shape

(103, 3)